// spriteConfig.js
// Describes the layout of assets/textures/player/character-spritesheet.png
// Generated by the Universal LPC Spritesheet Character Generator.
// Sheet is 832x3456 -> 13 columns x 54 rows, 64x64px frames.
// Frame index for Phaser (spritesheet loader) = row * COLS + col.

export const FRAME_SIZE = 64;
export const COLS = 13;

// Row where each 4-direction animation block starts, and how many
// frame columns are used per direction. Confirmed by inspecting the
// actual uploaded sheet's pixel content, not guessed.
export const ANIM_BLOCKS = {
  spellcast: { row: 0, frames: 7 },
  thrust: { row: 4, frames: 8 },
  walk: { row: 8, frames: 9 },
  slash: { row: 12, frames: 6 }, // used as KICK
  shoot: { row: 16, frames: 13 },
  hurt: { row: 20, frames: 6, singleRow: true }, // south-facing only
  climb: { row: 21, frames: 6, singleRow: true },
  idle: { row: 22, frames: 2 },
  jump: { row: 26, frames: 5 },
  sit: { row: 30, frames: 3 },
  emote: { row: 34, frames: 3 },
  run: { row: 38, frames: 8 },
  combat_idle: { row: 42, frames: 2 },
  backslash: { row: 46, frames: 13 },
  halfslash: { row: 50, frames: 6 }, // used as PUNCH
};

// Direction -> row offset within a 4-row animation block.
export const DIR = {
  up: 0,
  left: 1,
  down: 2,
  right: 3,
};

// The animations we're actually wiring up for Phase 1, and which
// LPC block + framerate/loop behaviour each one maps to.
export const PLAYER_ANIMS = {
  idle: { block: 'idle', frameRate: 3, repeat: -1 },
  walk: { block: 'walk', frameRate: 10, repeat: -1 },
  jump: { block: 'jump', frameRate: 12, repeat: 0 },
  punch: { block: 'halfslash', frameRate: 16, repeat: 0 },
  kick: { block: 'slash', frameRate: 14, repeat: 0 },
  hurt: { block: 'hurt', frameRate: 10, repeat: 0, singleRow: true },
};

/**
 * Compute the [start, end] Phaser frame indices for a given animation
 * block + direction.
 */
export function frameRange(blockName, direction) {
  const block = ANIM_BLOCKS[blockName];
  if (!block) throw new Error(`Unknown sprite block "${blockName}"`);

  const row = block.singleRow ? block.row : block.row + DIR[direction];
  const start = row * COLS;
  const end = start + block.frames - 1;
  return { start, end };
}
